apiVersion: v1
kind: Pod
metadata:
 name: podman
 annotations:
   io.kubernetes.cri-o.Devices: "/dev/fuse"
spec:
  containers:
  - name: podman
    image: quay.io/cgruver0/podman-in-a-pod:latest
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - "SETUID"
        - "SETGID"
    volumeMounts:
    - name: containerfile
      mountPath: /home/user/image
  volumes:
  - name: containerfile
    configMap:
      name: image-config-map
      defaultMode: 444
      items:
      - key: containerfile
        path: Containerfile

      